FROM php:8.1-fpm-alpine

RUN apk add --no-cache \
    mariadb && \
    docker-php-ext-install -j$(nproc) mysqli pdo pdo_mysql && \
    docker-php-ext-enable opcache && \
    docker-php-source delete

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

COPY docker-php-defaults.ini "$PHP_INI_DIR/conf.d"

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# COPY src/ /var/www/html/

